EasyVpyska/EasyVpyska.WebUI.Frontend/Controllers/LayoutController.cs
using EasyVpyska.WebUI.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EasyVpyska.WebUI.Frontend.Controllers
{
    public class LayoutController : Controller
    {
        #region Fields
        private readonly ISecurityManager _securityManager;
        #endregion
        
        #region Constructor
        public LayoutController(ISecurityManager securityManager)
        {
            _securityManager = securityManager;
        }
        #endregion

        #region Methods
        [ChildActionOnly]
       public ActionResult PartialAuthenticated()
        {
            bool userLog = _securityManager.IsCurrentUserAuthenticated();
            ViewBag.UserLog = userLog;
            if (userLog)
            {
                ViewBag.loginUsersId = _securityManager.GetCurrentUserId();
            }

            return PartialView("PartialAuthenticated");
        }

        [ChildActionOnly]
        public ActionResult PartialLogOut()
        {
            bool userLog = _securityManager.IsCurrentUserAuthenticated();
            ViewBag.UserLog = userLog;
    
            return PartialView("PartialLogOut");
        }
        #endregion
    }
}

EasyVpyska/EasyVpyska.WebUI.Frontend/Controllers/LogInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using EasyVpyska.WebUI;
using EasyVpyska.WebUI.Abstract;
using System.Net.Mail;
using System.Net;

namespace EasyVpyska.WebUI.Frontend.Controllers
{
    public class LogInController : Controller
    {
        #region Fields
        private readonly ISecurityManager _securityManager;
        private readonly IEmailService _emailService;
        #endregion

        #region Constructor
        public LogInController(ISecurityManager securityManager, IEmailService emailService)
        {
            _securityManager = securityManager;
            _emailService = emailService;
        }
        #endregion

        #region Methods

        [HttpPost]
        public ActionResult LogIn(string name, string password)
        {
            int userId = -1;
            bool blocked = false;
            bool authenticated = false;

            IDictionary<string, string> violations = new Dictionary<string, string>();

            if (_securityManager.Authentication(name, password))
            {
                if (!_securityManager.IsUserEnabled(name))
                {
                    blocked = true;

                    violations.Add(new KeyValuePair<string, string>("password",
                        "User is blocked"));
                }
                else
                {
                    _securityManager.SetAuthCookie(name, true);

                    userId = _securityManager.GetUserId(name);

                    authenticated = true;
                }
            }
            else
            {
                violations.Add(new KeyValuePair<string, string>("password",
                    "Incorrect Login/Password combination"));
            }



            var data = new
            {
                blocked = blocked,
                authenticated = authenticated,
                userId = userId,
                violations = violations
            };

            var serializator =
                new System.Web.Script.Serialization.JavaScriptSerializer();

            string dataJson = serializator.Serialize(data);

            return Content(dataJson, "application/json");
        }

        [HttpPost]
        public ActionResult LogOut()
        {
            if (_securityManager.IsCurrentUserAuthenticated())
            {
                _securityManager.SignOut();

                return Json(new { logOutSuccess = true });
            }

            return Json(new { logOutSuccess = false });
        }

        [HttpGet]
        public ActionResult IsCurrentUserSigned()
        {
            if (_securityManager.IsCurrentUserAuthenticated())
            {
                return Json(new { authenticated = true });
            }

            return Json(new { authenticated = false });
        }

        [HttpPost]
        public ActionResult SendMailToAdmin(string message)
        {
            try
            {
                _emailService.SendEmail("easyvpyska@gmail.com", "Feedback from user", "Text:<br /><br />" + message);
                return Json(new { result = true });
            }
            catch (Exception e)
            {
                NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();
                logger.Error(e.Message);
                return Json(new { result = true });
            }
        }
        #endregion
    }
}

EasyVpyska/EasyVpyska.WebUI.Frontend/Controllers/SearchAdController.cs
using EasyVpyska.Entities;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using EasyVpyska.WebUI.Abstract;
using EasyVpyska.Repositories.Abstract;
using EasyVpyska.Repositories.Sql;

namespace EasyVpyska.WebUI.Frontend.Controllers
{
    
    public class SearchAdController : Controller
    {
        #region Fields
        private readonly IAdRepository _adRepository;
        private readonly IUserRepository _userRepository;
        private readonly IImageService _imageService;
        #endregion

        #region Constructor
        public SearchAdController(IAdRepository adRepository, IUserRepository userRepository,
            IImageService imageService)
        {
            _imageService = imageService;
            _adRepository = adRepository;
            _userRepository = userRepository;
        }
        #endregion

        #region Methods
        //
        // GET: /FindAd/
        [HttpGet]
        public ActionResult Index()
        {
            AdFilter filter = new AdFilter();
            filter.IsEnabled = true;
            filter.IsActive = true;
            filter.Start = DateTime.Now;

            List<Ad> adsList = _adRepository.GetAds(filter, 1, 6);

            for (int i = 0; i < adsList.Count; i++)
            {
                var image = _imageService.LoadPhoto(adsList[i].Author.Id);

                if (image.File != null)
                {
                    var base64Image = "data:image/jpg;base64," + Convert.ToBase64String(image.File);
                    adsList[i].Author.ImageString = base64Image;
                }
                else
                {
                    adsList[i].Author.ImageString = @"/Styles/Image/icon-user.png";
                }
            }

            ViewBag.ListOfAds = adsList;
           
            ViewBag.Count = _adRepository.CountSuitableAds(filter);
               
            return View();
        }


        [HttpPost]
        public PartialViewResult Filter(string typeAd, string city, string ArrivalDate, string leaveDate, int page, int ads)
        {
            bool? typeOfAd;
            DateTime? arriveDt = DateTime.Now;
            DateTime? leaveDt = null;

            if (typeAd.ToLower() == "search")
            {
                typeOfAd = true;

            }
            else if (typeAd.ToLower() == "offer")
            {
                typeOfAd = false;
            }
            else
            {
                typeOfAd = null;            
            }

            if (ArrivalDate != String.Empty)
            {
                 arriveDt = DateTime.ParseExact(ArrivalDate, "dd.MM.yyyy", null);
            }

            if (leaveDate != String.Empty)
            {
                leaveDt = DateTime.ParseExact(leaveDate, "dd.MM.yyyy", null);
            }
            if (city== String.Empty)
            {
                city = null;
            }

            AdFilter filter = new AdFilter();
            filter.IsRequest = typeOfAd;
            filter.IsEnabled = true;
            filter.AuthorId = null;
            filter.Town = city;
            filter.Start = arriveDt;
            filter.Finish = leaveDt;
            filter.IsActive = true;

            List<Ad> adsFilterList = _adRepository.GetAds(filter, page, ads);

            for (int i = 0; i < adsFilterList.Count; i++)
            {
                var image = _imageService.LoadPhoto(adsFilterList[i].Author.Id);

                if (image.File != null)
                {
                    var base64Image = "data:image/jpg;base64," + Convert.ToBase64String(image.File);
                    adsFilterList[i].Author.ImageString = base64Image;
                }
                else
                {
                    adsFilterList[i].Author.ImageString = @"/Styles/Image/icon-user.png";
                }
            }            

            ViewBag.Count = _adRepository.CountSuitableAds(filter);

            ViewBag.ListOfAds = adsFilterList;
            
            return PartialView("PartialSearchResult");
        }
        #endregion

    }
}

EasyVpyska/EasyVpyska.WebUI.Frontend/Views/Shared/About.cshtml
<div id="dialog-about" title="About us">
    <div class="about">
        <p>Our site was created to find new friends and opportunities. 
        No more need to call the hotel and distant relatives. 
        Just Leave the announcement of finding accommodation for the night.
         Or invite you to spend the night travelers.            
        </p>
        <p style="text-align:center">Let's help each other!</p>
    </div>
</div>

EasyVpyska/EasyVpyska.WebUI.Frontend/Views/Shared/Feedback.cshtml
<div id="dialog-feedback" title="Write to us">
    <div class="writeMessage">
        <div class="textarea textarea--kozakura">
            <textarea class="textarea__field textarea__field--kozakura" rows="3" cols="45" name="message" id="message" style="resize: none;"></textarea>
            <label class="textarea__label textarea__label--kozakura" for="message">
                <span class="textarea__label-content textarea__label-content--kozakura" data-content="message">Message</span>
            </label>
            <svg class="textarea-graphic textarea-graphic--kozakura" width="400%" height="400%" viewBox="0 0 1200 160" preserveAspectRatio="none">
                <path d="M1200,9c0,0-305.005,0-401.001,0C733,9,675.327,4.969,598,4.969C514.994,4.969,449.336,9,400.333,9C299.666,9,0,9,0,9v43c0,0,299.666,0,400.333,0c49.002,0,114.66,3.484,197.667,3.484c77.327,0,135-3.484,200.999-3.484C894.995,52,1200,52,1200,52V9z" />
            </svg>
        </div>
        <button id="sendMail" type="button" class="button button--wayra-s button--border-thick button--text-upper button--size-xs" style="margin-top:-25px;; margin-bottom:0;margin-left:430px;">SEND</button>
        </div>
    <div class="thnks" style="display:none">
        <p style="margin-top:15%; text-align: center; font-size:28px; color:white;">Thank you!</p>
     </div>
</div>

EasyVpyska/EasyVpyska.WebUI.Frontend/Views/Shared/LogIn.cshtml
    <div id="dialog-modal" title="Login dialog">
        <form class="cmxform" id="loginForm" method="get" enctype="multipart/form-data">
            <p style="margin:-15px 0 0 0;">
                <span class="input input--kozakura">
                    <input class="input__field input__field--kozakura" type="text" id="login" name="login" autocomplete="on" />
                    <label class="input__label input__label--kozakura" for="auth-login">
                        <span class="input__label-content input__label-content--kozakura" data-content="Login">Login</span>
                    </label>
                    <svg class="graphic graphic--kozakura" width="300%" height="100%" viewBox="0 0 1200 60" preserveAspectRatio="none">
                        <path d="M1200,9c0,0-305.005,0-401.001,0C733,9,675.327,4.969,598,4.969C514.994,4.969,449.336,9,400.333,9C299.666,9,0,9,0,9v43c0,0,299.666,0,400.333,0c49.002,0,114.66,3.484,197.667,3.484c77.327,0,135-3.484,200.999-3.484C894.995,52,1200,52,1200,52V9z" />
                    </svg>
                </span>
            </p>
            <p style="margin: -25px 0 0 0;">
                <span class="input input--kozakura">
                    <input class="input__field input__field--kozakura" type="password" id="password" name="password" />
                    <label class="input__label input__label--kozakura" for="pass">
                        <span class="input__label-content input__label-content--kozakura" data-content="Password">Password</span>
                    </label>
                    <svg class="graphic graphic--kozakura" width="300%" height="100%" viewBox="0 0 1200 60" preserveAspectRatio="none">
                        <path d="M1200,9c0,0-305.005,0-401.001,0C733,9,675.327,4.969,598,4.969C514.994,4.969,449.336,9,400.333,9C299.666,9,0,9,0,9v43c0,0,299.666,0,400.333,0c49.002,0,114.66,3.484,197.667,3.484c77.327,0,135-3.484,200.999-3.484C894.995,52,1200,52,1200,52V9z" />
                    </svg>
                </span>
            </p>
            <span class="sign-buttons">
                <button id="btnSignIn" type="button" class="button button--wayra-s button--border-thick button--text-upper button--size-xs">Sign in</button>

                <button id="btnSignUp" type="button" class="button button--wayra-s button--border-thick button--text-upper button--size-xs">Sign up</button>
            </span>
        </form>
</div>

EasyVpyska/EasyVpyska.WebUI.Frontend/Views/Shared/PartialAdsInUserProfile.cshtml
@{   
    int? ads = ViewBag.Ads ?? 1;
    
    int? count = ViewBag.Count ?? default(int?);
    List<EasyVpyska.Entities.Ad> listAds = ViewBag.ListOfAds;

    bool? LoginedUser = ViewBag.LoginUser ?? false;
    int? UserId = ViewBag.idLoginUser ?? default(int?);
    
    }
    
<input type="hidden" id="nextAds" value=@ads>
<input type="hidden" id="allAds" value=@count>
    @if(listAds != null)
    {
        foreach (var l in listAds)
        {
            if ((LoginedUser == true) && (UserId == l.Author.Id))
            { 
            <div class="ad">
                <input type="hidden" id="AdId" value=@l.Id>
                <div class="user-actions"> 
                    <span id="suitable" data-id="@l.Id">Suitable ads&ensp;<i class="fa fa-binoculars"></i></span>
                </div>  
                <span id="city">@l.Town</span>
                <p id="date">@l.BeginTime.ToString("dd.MM.yyyy") - @l.EndTime.ToString("dd.MM.yyyy")</p>
                <p class="title"><a class="title" href="/AdDetails/index/@l.Id">@l.Title</a></p>
                <div id="text">@l.Description</div>
                @if(l.IsActive)
                {
                  <span class="status-en">ACTIVE</span>                    
                }
                else
                {
                    <span class="status-dis">INACTIVE</span>
                }               
                <span class="views">Viewers: @l.Views </span>
                <div class="user-actions">
                    @if (l.IsActive)
                    { 
                       <span id="disable" data-id="@l.Id" >Disable&ensp;<i class="fa fa-eye-slash"></i></span>
                    }
                    else 
                    {
                        <span id="enable" data-id="@l.Id">Enable&ensp;<i class="fa fa-eye"></i></span>
                    }            
                    
                    @*<span id="delete" data-id="@l.Id">Delete&ensp;<i class="fa fa-trash"></i></span>*@    
                </div>           
                @if (l.Subscribers.Count > 0)
                {
                <p style="margin:0 0 0 15px; font-size: 14px;">
                    Your subscribers:
                    @foreach (var s in l.Subscribers)
                    {
                        if(l.Subscribers.Count > 1)
                        { 
                            <a class="subscribers" href="/User/Index/@s.UserId"> @s.Name,</a>
                        }
                        else
                        { 
                            <a class="subscribers" href="/User/Index/@s.UserId">@s.Name</a>
                        }
                    }
                </p>
                }     
            </div>        
            }
            else      
            {
                <div class="ad">
                    <input type="hidden" id="AdId" value=@l.Id>
                    <span id="city">@l.Town</span>
                    <p id="date">@l.BeginTime.ToString("dd.MM.yyyy") - @l.EndTime.ToString("dd.MM.yyyy")</p>
                    <p class="title"><a class="title" href="/AdDetails/index/@l.Id">@l.Title</a></p>
                    <div id="text">@l.Description</div>           
                </div>
            }
        
        }     
    }
    @if ((count != null) && (listAds.Count >0))
    {
        <div class="next" >
            <button type="button" class="button button--wayra-m button--border-thick button--text-upper button--size-xs" id="next-button">Show next ads</button>
        </div>
    }
    else
    { 
        <div class="ad">
            <p style="text-align:center">Sorry, you haven`t ads</p>   
        </div>
    }

EasyVpyska/EasyVpyska.WebUI.Frontend/Views/Shared/PartialAuthenticated.cshtml
@{
    bool? UserLogin=ViewBag.UserLog ?? false;
    int? UserId = ViewBag.loginUsersId ?? default(int?);
}

@if (UserLogin == true)
{
    <a href="/User/Index/@ViewBag.loginUsersId" id="profile"><i class="fa fa-fw fa fa-user"></i><span>Profile</span></a>
}
else
{
    <a href="#" id="logIn"><i class="fa fa-sign-in"></i><span>Log In</span></a>
}

EasyVpyska/EasyVpyska.WebUI.Frontend/Views/Shared/PartialLogOut.cshtml
@{
    bool? UserLogin = ViewBag.UserLog ?? false;
}

@if (UserLogin == true)
{
    <a href="#" id="logOut"><i class="fa fa-sign-out"></i><span>Log Out</span></a>
}

EasyVpyska/EasyVpyska.WebUI.Frontend/Views/Shared/PartialSearchResult.cshtml
@{    
    List<EasyVpyska.Entities.Ad> listAds = ViewBag.ListOfAds;

    int? Count = ViewBag.Count ?? default(int?);    
}

<input type="hidden" id="count" value="@Count" />
@if(listAds.Count != 0)
{ 
<ul>
    @foreach (var l in listAds)
    {
        <li>           
            <a class="cbp-vm-image" href="/AdDetails/index/@l.Id">
                <img src=@l.Author.ImageString />
            </a>
            <h3 class="cbp-vm-title">
                @if (l.IsRequest)
                {
                    <span style="font-size: 14px; color: rgba(0,0,0,0.3)">Looking for</span>
                }
                else
                {
                    <span style="font-size: 14px; color: rgba(0,0,0,0.3)">Offer</span>
                }
            <br />
            @l.Title
        </h3>
            <div class="cbp-vm-city">
                <p style="margin:0">From: @l.BeginTime.ToString("dd.MM.yy")</p>
                <p style ="margin:0">To: @l.EndTime.ToString("dd.MM.yy")</p>
                <strong>@l.Town</strong>
            </div>
            <div class="cbp-vm-details">
                @l.Description
            </div>
            <a class="cbp-vm-add" href="/AdDetails/index/@l.Id">View Details</a>
        </li>
    }
</ul>
}
else
{
    <p class="no-result">No results for your request</p>
}

EasyVpyska/EasyVpyska.WebUI.Frontend/Views/Shared/PartialSuitableAds.cshtml
@{
    List<EasyVpyska.Entities.Ad> ads = ViewBag.SuitableAds;
}

@if(ads!= null && ads.Count>0)
{ 
    <div id="piece">
    @foreach (var a in ads)
    {
        <h3>@a.Title</h3>
        <div>
            <p id="suitableAuthor"><a href="/User/Index/@a.Author.Id">@a.Author.FirstName</a></p>
            <p id="suitableAge">Age: @a.Author.Age</p>
            <p id="suitableDate">@a.BeginTime.ToString("dd.MM.yyyy") - @a.EndTime.ToString("dd.MM.yyyy")</p>
            <p id="suitableDescription">@a.Description</p>
            <span id="suitableCity">@a.Town</span>
            <p id="suitableLink"><a href="/AdDetails/Index/@a.Id">View ad</a></p>
        </div>
    }
        </div>
        <p id="searchLink"><a href="@Url.Action("Index", "SearchAd")">View more</a></p>
    }
else
{
    <p id="sorry-message">Sorry, we can`t find any ads for you. Try later!</p>    
}

EasyVpyska/EasyVpyska.WebUI.Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />    
    <link rel="shortcut icon" href="~/Styles/Image/icon_logo.png" type="image/png">
    <title>EasyVpyska</title>
    <link href="~/Fonts/font-awesome-4.2.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon" />
    <script src="~/Scripts/libs/classie/modernizr.custom.2.8.3.js"></script>

    @System.Web.Optimization.Styles.Render("~/bundles/Layout")
    
    @RenderSection("Styles", false)
</head>
<body>
    <div class="container">
        <div class="menu-wrap">
            <nav class="menu">
                <div class="icon-list">
                    <a href="@Url.Action("Index","Home")"><i class="fa fa-fw fa fa-building ev"></i><span class="ev">EasyVpyska</span></a>
                    
                    @(Html.Action("PartialAuthenticated", "Layout"))                                               

                    @RenderSection("Menu")       
                    <a href="#" id="feedback"><i class="fa fa-fw fa-envelope-o"></i><span>Feedback</span></a>
                    <a href="#" id="about"><i class="fa fa-fw fa-comment-o"></i><span>About</span></a>                           
                    @(Html.Action("PartialLogOut", "Layout"))
                    
                </div>
            </nav>
            <button class="close-button" id="close-button">Close Menu</button>
        </div>       
        <button class="menu-button" id="open-button" title="Open Menu"></button>

        @RenderSection("Title", false)      
        
        @RenderBody()
    </div>

    @{Html.RenderPartial("LogIn");}
    @{Html.RenderPartial("Feedback");}
    @{Html.RenderPartial("About");}

    @System.Web.Optimization.Scripts.Render("~/bundles/LayoutPage")
    @RenderSection("Scripts", false)
</body>

</html>