EasyVpyska/EasyVpyska.WebUI.Frontend/Controllers/CreateAdController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using System.Web.Script.Serialization;

using EasyVpyska.Entities;
using EasyVpyska.Repositories.Abstract;
using EasyVpyska.Repositories.Sql;
using EasyVpyska.WebUI.Abstract;
using System.Net.Mail;
using System.Net;
using System.Threading.Tasks;

namespace EasyVpyska.WebUI.Frontend.Controllers
{

    public class CreateAdController : Controller
    {
        #region Fields
        private readonly IAdRepository _adRepository;
        private readonly ISecurityManager _securityManager;
        private readonly IUserRepository _userRepository;
        private readonly IEmailService _emailService;
        #endregion

        #region Constructor
        public CreateAdController(IUserRepository userRepository, ISecurityManager securityManager, IAdRepository adRepository, IEmailService emailService)
        {
            _adRepository = adRepository;
            _securityManager = securityManager;
            _userRepository = userRepository;
            _emailService = emailService;
        }
        #endregion

        #region Methods
        //
        // GET: /CreateAd/
        [HttpGet]
        public ActionResult Index()
        {

            bool login = _securityManager.IsCurrentUserAuthenticated();
            ViewBag.UserLogin = login;
            if (login)
            {
                ViewBag.LoginUserId = _securityManager.GetCurrentUserId();
            }
            return View();
        }

        [HttpPost]
        public ActionResult Create(string adJson)
        {
            int adId = -1;
            JavaScriptSerializer _jsonSerializer = new JavaScriptSerializer();
            var ad = _jsonSerializer.Deserialize<Ad>(adJson);
            var violations = new Dictionary<string, string>();

            CheckNewAdRules(ad, violations);

            if (violations.Count == 0)
            {
                adId = _adRepository.CreateAd(ad);
            }

            var data = new
            {
                adId = adId,
                violations = violations
            };

            var serializator =
                new System.Web.Script.Serialization.JavaScriptSerializer();

            string dataJson = serializator.Serialize(data);

            return Content(dataJson, "application/json");
        }

        [HttpPost]
        public ActionResult CreateWithRegister(string adJson, string userJson)
        {
            int adId = -1;

            string password = this.CreateRandomPassword();
            var violations = new Dictionary<string, string>();

            JavaScriptSerializer _jsonSerializer = new JavaScriptSerializer();
            var ad = _jsonSerializer.Deserialize<Ad>(adJson);
            var user = _jsonSerializer.Deserialize<User>(userJson);

            AdAuthor author = new AdAuthor();

            ad.Author = author;
            
            user.Role = "user";
            user.Status = true;

            int register = -1;

            CheckNewUserRules(user, violations);
            CheckNewAdRules(ad, violations);

            if (violations.Count == 0)
            {
                register = _securityManager.RegistrateUser(user, password);

                if (register != -1)
                {
                    Task emailTask = Task.Run(() =>
                    {
                        try
                        {
                            string mailSubject = "Congratulation! You have been registrated on our site!";
                            string mailBody = "Your login: " + user.Login + "<br /><br />"
                                   + "Your password: " + password + "<br /><br />"
                                   + "Please, visit our <a href='easyvpyska.somee.com'>site</a> and edit your password and profile." + "<br /><br />"
                                   + "Best regards, EasyVpyska";
                            _emailService.SendEmail(user.Email, mailSubject, mailBody);
                        }
                        catch (Exception e)
                        {
                            NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();
                            logger.Error(e.Message);

                        }
                    });

                    if (ad.Author.Id == 0)
                    {
                        ad.Author.Id = _userRepository.GetUserId(user.Login);
                    }

                    adId = _adRepository.CreateAd(ad);
                }
            }

            var data = new
            {
                adId = adId,
                violations = violations
            };

            var serializator =
                new System.Web.Script.Serialization.JavaScriptSerializer();

            string dataJson = serializator.Serialize(data);


            return Content(dataJson, "application/json");

        }

        [HttpPost]
        public JsonResult IsEmailAwaliable(string txtEmail)
        {
            #region Validation
            if (txtEmail == null)
            {
                throw new ArgumentNullException();
            }
            #endregion

            if (_userRepository.IsEmailExist(txtEmail))
            {
                return new JsonResult { Data = false };
            }

            return new JsonResult { Data = true };
        }

        #endregion

        #region Helpers

        private string CreateRandomPassword()  
        {
            string _allowedChars = "abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNOPQRSTUVWXYZ0123456789-";
            Random randNum = new Random((int)DateTime.Now.Ticks);  //Don't forget to seed your random, or else it won't really be random
            char[] chars = new char[8];
            
            for (int i = 0; i < 8; i++)
            {
                chars[i] = _allowedChars[randNum.Next(_allowedChars.Length)];                
            }
            return new string(chars);
        }
        private void CheckNewUserRules(User user,
            IDictionary<string, string> violations)
        {
            CheckWordRules(user.FirstName, "txtName", violations);

            CheckEmailRules(user.Login, "txtEmail", violations);
            CheckEmailRules(user.Email, "txtEmail", violations);

            CheckBirthDateRules(user.DateOfBirth, "txtBirthDate", violations);
        }

        private void CheckNewAdRules(Ad ad,
            IDictionary<string, string> violations)
        {
            CheckAddressRules(ad, "txtAddress", violations);

            CheckFutureDateRules(ad.BeginTime, "txtArrivalDate", violations);
            CheckFutureDateRules(ad.EndTime, "txtLeavingDate", violations);

            CheckSettlementDatesRules(ad.BeginTime, ad.EndTime, "txtLeavingDate", violations);

            CheckTextLenth(ad.Address, "txtAddress", violations, 64);
            CheckTextLenth(ad.Country, "txtAddress", violations, 64);
            CheckTextLenth(ad.Town, "txtAddress", violations, 64);
            CheckTextLenth(ad.Title, "txtTitle", violations, 25);
            CheckTextLenth(ad.Description, "txtDescription", violations, 256);
        }


        private void CheckAddressRules(Ad ad, string fieldName,
            IDictionary<string, string> violations)
        {
            var regex = new Regex("^[a-zA-Z]+$");

            if (string.IsNullOrEmpty(ad.Country)
                && !violations.ContainsKey(fieldName))
            {
                violations.Add(new KeyValuePair<string, string>(fieldName,
                    "Enter country name please."));
            }

            if (string.IsNullOrEmpty(ad.Town)
                && !violations.ContainsKey(fieldName))
            {
                violations.Add(new KeyValuePair<string, string>(fieldName,
                    "Enter town name please."));
            }
        }

        private void CheckWordRules(string word, string fieldName,
           IDictionary<string, string> violations,
           int minLength = 3,
           int maxLength = 64)
        {
            var regex = new Regex("^[a-zA-Z]+$");

            if (string.IsNullOrEmpty(word)
                && !violations.ContainsKey(fieldName))
            {
                violations.Add(new KeyValuePair<string, string>(fieldName,
                    "Enter value please."));
            }
            if (word != null
                && word.Length < minLength
                && !violations.ContainsKey(fieldName))
            {
                violations.Add(new KeyValuePair<string, string>(fieldName,
                    "Please enter at least " + minLength.ToString() +
                    " 3 characters."));
            }
            if (word != null
                && word.Length > maxLength
                && !violations.ContainsKey(fieldName))
            {
                violations.Add(new KeyValuePair<string, string>(fieldName,
                    "Please enter no more than " + maxLength.ToString() +
                    " characters."));
            }
            if (word != null
                && !regex.IsMatch(word)
                && !violations.ContainsKey(fieldName))
            {
                violations.Add(new KeyValuePair<string, string>(fieldName,
                    "Please use just english letters."));
            }
        }

        private void CheckEmailRules(string email, string fieldName,
            IDictionary<string, string> violations)
        {
            var regex = new Regex("^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9]+"
                + "(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");

            if (string.IsNullOrEmpty(email)
                && !violations.ContainsKey(fieldName))
            {
                violations.Add(new KeyValuePair<string, string>(fieldName,
                    "Enter value please."));
            }
            if (email != null

EasyVpyska/EasyVpyska.WebUI.Frontend/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using EasyVpyska.Entities;
using EasyVpyska.Repositories.Abstract;
using EasyVpyska.Repositories.Sql;

using EasyVpyska.WebUI.Frontend.Models;
 

namespace EasyVpyska.WebUI.Frontend.Controllers
{
          
    public class MapController : Controller
    {
        #region Fields
        private readonly IAdRepository _adRepository;
        #endregion

        #region Constructor
        public MapController(IAdRepository adRepository)
        {
            _adRepository = adRepository;
        }
        #endregion

        #region Methods
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetAddresses()
        {
            List<Ad> adsList = _adRepository.GetAllAdsByType(false);

            List<AdAddressModel> addresses = new List<AdAddressModel>();

            adsList.ForEach(ad => addresses.Add(new AdAddressModel() { Address = ad.Town + " " + ad.Address, Id = ad.Id }));

            return Json(new
            {
                startPosition = new { latitude = 49.6594482, longitude = 31.5560814, zoom = 6 },
                addresses
            });
        }

        [HttpPost]
        public ActionResult GetAdFullInfo(int Id)
        {
            var Ad = _adRepository.GetAd(Id);         

            string name = "";           
            string description = "";
            string from = "";
            string to = "";
            string adLink = "";


            if (Ad != null)
            {
                description = Ad.Description;
                from = Ad.BeginTime.ToShortDateString();
                to = Ad.EndTime.ToShortDateString();
                adLink = Ad.Id.ToString();
            }

            if (Ad.Author.FirstName != null)
            {
                name = Ad.Author.FirstName;                 
                
            }

            return Json(new
            {
                name = name,                           
                from = from,
                to = to,
                description = description,
                adLink = adLink
            });
        }
        #endregion
    }
}

EasyVpyska/EasyVpyska.WebUI.Frontend/Controllers/SearchAdController.cs
using EasyVpyska.Entities;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using EasyVpyska.WebUI.Abstract;
using EasyVpyska.Repositories.Abstract;
using EasyVpyska.Repositories.Sql;

namespace EasyVpyska.WebUI.Frontend.Controllers
{
    
    public class SearchAdController : Controller
    {
        #region Fields
        private readonly IAdRepository _adRepository;
        private readonly IUserRepository _userRepository;
        private readonly IImageService _imageService;
        #endregion

        #region Constructor
        public SearchAdController(IAdRepository adRepository, IUserRepository userRepository,
            IImageService imageService)
        {
            _imageService = imageService;
            _adRepository = adRepository;
            _userRepository = userRepository;
        }
        #endregion

        #region Methods
        //
        // GET: /FindAd/
        [HttpGet]
        public ActionResult Index()
        {
            AdFilter filter = new AdFilter();
            filter.IsEnabled = true;
            filter.IsActive = true;
            filter.Start = DateTime.Now;

            List<Ad> adsList = _adRepository.GetAds(filter, 1, 6);

            for (int i = 0; i < adsList.Count; i++)
            {
                var image = _imageService.LoadPhoto(adsList[i].Author.Id);

                if (image.File != null)
                {
                    var base64Image = "data:image/jpg;base64," + Convert.ToBase64String(image.File);
                    adsList[i].Author.ImageString = base64Image;
                }
                else
                {
                    adsList[i].Author.ImageString = @"/Styles/Image/icon-user.png";
                }
            }

            ViewBag.ListOfAds = adsList;
           
            ViewBag.Count = _adRepository.CountSuitableAds(filter);
               
            return View();
        }


        [HttpPost]
        public PartialViewResult Filter(string typeAd, string city, string ArrivalDate, string leaveDate, int page, int ads)
        {
            bool? typeOfAd;
            DateTime? arriveDt = DateTime.Now;
            DateTime? leaveDt = null;

            if (typeAd.ToLower() == "search")
            {
                typeOfAd = true;

            }
            else if (typeAd.ToLower() == "offer")
            {
                typeOfAd = false;
            }
            else
            {
                typeOfAd = null;            
            }

            if (ArrivalDate != String.Empty)
            {
                 arriveDt = DateTime.ParseExact(ArrivalDate, "dd.MM.yyyy", null);
            }

            if (leaveDate != String.Empty)
            {
                leaveDt = DateTime.ParseExact(leaveDate, "dd.MM.yyyy", null);
            }
            if (city== String.Empty)
            {
                city = null;
            }

            AdFilter filter = new AdFilter();
            filter.IsRequest = typeOfAd;
            filter.IsEnabled = true;
            filter.AuthorId = null;
            filter.Town = city;
            filter.Start = arriveDt;
            filter.Finish = leaveDt;
            filter.IsActive = true;

            List<Ad> adsFilterList = _adRepository.GetAds(filter, page, ads);

            for (int i = 0; i < adsFilterList.Count; i++)
            {
                var image = _imageService.LoadPhoto(adsFilterList[i].Author.Id);

                if (image.File != null)
                {
                    var base64Image = "data:image/jpg;base64," + Convert.ToBase64String(image.File);
                    adsFilterList[i].Author.ImageString = base64Image;
                }
                else
                {
                    adsFilterList[i].Author.ImageString = @"/Styles/Image/icon-user.png";
                }
            }            

            ViewBag.Count = _adRepository.CountSuitableAds(filter);

            ViewBag.ListOfAds = adsFilterList;
            
            return PartialView("PartialSearchResult");
        }
        #endregion

    }
}

EasyVpyska/EasyVpyska.WebUI.Frontend/Views/AdDetails/Index.cshtml
@{
     
    Layout = "~/Views/Shared/_Layout.cshtml";

    EasyVpyska.Entities.Ad ad = ViewBag.Ad ?? null;

    int? CurrentUserId = ViewBag.CurrentUserId ?? null;
    bool? IsSubscribe = ViewBag.IsSubscribe ?? false;

    bool check = false;
    if ((CurrentUserId != null) && (ad.Author.Id != null) && (ad.Author.Id != CurrentUserId) && (IsSubscribe==false))
    {
        check = true; 
    }
    
}

@section Styles{
@System.Web.Optimization.Styles.Render("~/bundles/details")
@System.Web.Optimization.Styles.Render("~/bundles/mapStyle")

}

@section Menu{    
    <a href="@Url.Action("Index","CreateAd") "><i class="fa fa-fw fa fa-plus"></i><span>Create an ad</span></a>
    <a href="@Url.Action("Index","SearchAd") "><i class="fa fa-fw fa fa-search"></i><span>Search an ad</span></a>
    <a href="@Url.Action("Index","Map")"><i class="fa fa-fw fa fa-globe"></i><span>Look ads at map</span></a>
 }

@section Title{
    <div class="pageTitle">
        <h1></h1>
    </div>
}

<div class="ad-content">
    <div class="ad-info">
        @if (check) { 
        <p id="subsRow"><a href="#" id="subs">Subscribe <i class="fa fa-check-square-o"></i></a></p>
        }
        @if (IsSubscribe==true)
        { 
            <p id="subsRow">You subscribed on this ad</p>
        }
        <div class="field">
            <div class ="ad-title">
                <p style="font-size: 18px; color: rgba(0,0,0,0.3);">Ad title:</p>
                <p style="font-weight: bold;">@ad.Title</p>
            </div>
          </div>
        <div class="field">
            <table class="author">
                <tr>
                    <td class="picture" rowspan="3">
                        <a href="/User/Index/@ad.Author.Id"><img src="@ViewBag.Image" /></a>
                    </td>
                    <td class="left">
                        Name:&ensp;@ad.Author.FirstName
                    </td>
                </tr>
                <tr>
                    <td class="left">
                        Age:&ensp;@ad.Author.Age
                    </td>
                </tr>
                <tr>
                    <td class="left">
                        Live in:&ensp;@ad.Author.Town
                    </td>
                </tr>
                <tr class="profile-link">
                    <td>
                        <a href="/User/Index/@ad.Author.Id">View author profile</a>
                    </td>
                    <td></td>
                </tr>
                </table>
            </div>
            <div class="field">
                <table>
                <tr>
                    <td colspan="2">
                        <p>Arrive to:&ensp;@ad.Town</p>
                    </td>
                </tr>
                <tr>
                    <td>Arrive Date:</td>
                    <td>Leave Date:</td>
                </tr>
                <tr>
                    <td>@ad.BeginTime.ToString("dd.MM.yyyy")</td>
                    <td>@ad.EndTime.ToString("dd.MM.yyyy")</td>
                </tr>
                <tr>
                    <td colspan="2">
                        <p>Description: &ensp;@ad.Description</p>
                    </td>
                </tr>

                </table>
                </div>
            </div>
    <p style="text-align:right; margin-top:-18px;">This ad was viewed @ad.Views times</p>

    <div id="map-canvas" style="height:600px"></div>
                
    <input type="hidden" id="Id" value=@ad.Id>


                <div class="field">
                    
                    <div class="comments">                 
                        <div class="new-comment">
                            <p>New comment:</p>
                            <div>
                                <textarea class="new-comment-text"></textarea>
                            </div>
                            <div class="validation"></div>
                            <div class="btn">
                                <button type="button" class="button button--wayra-m button--border-thick button--text-upper button--size-xs add-comment-button" value="Add Comment">Add Comment</button>
                            </div>
                        </div>

                        <div class="comm">    
                            <div id="fresh-comment">
                                </div>                      
                                @foreach (var c in ad.Comments)
                                {               
                                    if(c.IsEnabled)
                                    {                 
                                        <div class="old-comments">
                                            <p class="comment-author">@c.UserName</p>
                                            <p id="date">@c.Time.ToShortDateString()</p>
                                            <div id="comment">@c.Comment</div>
                                        </div>    
                                    }                            
                                }                            
                        </div>
                    </div>
                </div>
    </div>

    @section Scripts{
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAKJBwDFXO1LiooxmaiwcuWTx67P1S0mbs"></script>
        @System.Web.Optimization.Scripts.Render("~/bundles/AdDetails")
    }